query ListAllCustomers @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  customers {
    id
    name
    email
  }
}

mutation CreateNewProduct($name: String!, $price: Float!) @auth(expr: "auth.token.admin == true") {
  product_insert(data: {
    name: $name,
    price: $price
  })
}

query GetProductById($id: String!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  product(key: {id: $id}) {
    id
    name
    price
    description
  }
}

mutation UpdateCustomerEmail($id: String!, $newEmail: String!) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  customer_update(key: {id: $id}, data: {
    email: $newEmail
  })
}